project_id = "qzmjeftxpaseobkexekg"

[api]
enabled = true

[ai]
enabled = true

[functions.recommend-courses]
verify_jwt = false

[functions.generate-competency-model]
verify_jwt = false

[functions.chat-with-colleague]
verify_jwt = false
