project_id = "qzmjeftxpaseobkexekg"

[api]
enabled = true

[functions.recommend-courses]
verify_jwt = false

[functions.generate-competency-model]
verify_jwt = false

[functions.chat-with-colleague]
verify_jwt = false

[functions.conduct-interview]
verify_jwt = false

[functions.grant-management]
verify_jwt = true

[functions.ref-replicator]
verify_jwt = false

[functions.log-application-event]
verify_jwt = true

[functions.erase-candidate]
verify_jwt = true

[functions.seed-vacancy-stages]
verify_jwt = true

[functions.generate-candidate-report]
verify_jwt = true
