-- ============================================================
-- СКАСОВАНО / НЕ ЗАСТОСОВУВАТИ (no-op)
-- ============================================================
-- Ця міграція починала порт DSA-канону (MetaProfile-main) як модуль «Оцінка».
-- ПІСЛЯ дослідження C:\Projects\studio-performance-hub зʼясувалося, що там уже
-- побудовано повноцінну 360°/Assessment + Performance НА НАШОМУ стеку
-- (Vite+React+Supabase): competency/competency_indicator/grade, evaluation_cycle,
-- assessment_360 + rater + response + metric + narrative + campaign + функції
-- звітів/життєвого циклу тощо. Тому канон Assessment/Performance — це studio,
-- і ми зливаємо його схему, а не портуємо DSA з нуля.
--
-- DSA (кейс-метод + AI-оцінка кейсів) лишається як можливе ПІДСИЛЕННЯ 360 studio
-- пізніше. Схема dsa_* нижче НЕ створюється (файл залишено порожнім навмисно,
-- щоб не плодити паралельний канон). Див. docs/PORTAL-MODULES-PLAN.md.
select 1;
